/* Offline A1 data inspector. Display transforms do not change saved radiance. */
(function(){'use strict';
const D=JSON.parse(document.getElementById('a1-data').textContent),$=s=>document.getElementById(s),world=$('world'),regime=$('regime'),sun=$('sun'),exposure=$('exposure');
D.profiles=Object.fromEntries(Object.entries(D.profileRaw).map(([k,v])=>[k,JSON.parse(v)]));
for(const a of D.skies['moon-fair'].suns_deg){const o=document.createElement('option');o.value=a;o.textContent=a+'°';sun.append(o);}sun.value='45';
const pct=(v,n=4)=>(100*v).toFixed(n)+'%',num=(v,n=3)=>Number(v).toFixed(n),scientific=x=>Number(x).toExponential(3),km=x=>(x/1000).toFixed(x<1000?3:2)+' km';
function fit(canvas){const w=Math.round(canvas.clientWidth),h=Math.round(canvas.clientHeight);canvas.width=w;canvas.height=h;return {ctx:canvas.getContext('2d'),w,h};}
function active(){const id=world.value+'-'+regime.value;return {id,record:D.manifest.profiles.find(x=>x.id===id),sky:D.skies[id],profile:D.profiles[id]};}
function interpolate(a,e,az){const ny=a.elevations_deg.length,nx=a.azimuths_deg.length;let iy=Math.sqrt(Math.max(0,Math.min(90,e))/90)*(ny-1),ix=Math.max(0,Math.min(180,az))/180*(nx-1);const j=Math.min(ny-2,Math.floor(iy)),i=Math.min(nx-2,Math.floor(ix)),u=ix-i,v=iy-j,s=a.radiance_rgb[a.suns_deg.indexOf(Number(sun.value))];return [0,1,2].map(k=>(s[j][i][k]*(1-u)+s[j][i+1][k]*u)*(1-v)+(s[j+1][i][k]*(1-u)+s[j+1][i+1][k]*u)*v);}
function encode(x){const v=1-Math.exp(-Math.max(0,x)*2**Number(exposure.value)/6000);return Math.round(255*(v<=.0031308?12.92*v:1.055*v**(1/2.4)-.055));}
function skyDraw(sky){const {ctx,w,h}=fit($('sky')),image=ctx.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const c=interpolate(sky,90*(1-y/(h-1)),180*x/(w-1)),k=(y*w+x)*4;for(let j=0;j<3;j++)image.data[k+j]=encode(c[j]);image.data[k+3]=255;}ctx.putImageData(image,0,0);ctx.font='12px system-ui';ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(10,10,132,28);ctx.fillStyle='#fff';ctx.fillText('Single scattering only',18,29);}
function axes(ctx,w,h,title){ctx.fillStyle='#acbcc7';ctx.font='11px system-ui';ctx.fillText(title,8,14);ctx.strokeStyle='#40515d';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(54,27);ctx.lineTo(54,h-33);ctx.lineTo(w-15,h-33);ctx.stroke();}
function profileDraw(profile,record){const {ctx,w,h}=fit($('profile'));ctx.clearRect(0,0,w,h);axes(ctx,w,h,'Molecule number density / surface density');const top=profile.upper.top_m,maxZ=top/1000,n0=profile.rows[0].numberTotal_m3,x=n=>54+Math.max(0,Math.min(1,(Math.log10(Math.max(1e-8,n/n0))+8)/8))*(w-69),y=z=>27+(1-z/top)*(h-60);ctx.font='10px system-ui';for(let i=0;i<=4;i++){const xx=54+i*(w-69)/4;ctx.fillStyle='#acbcc7';ctx.fillText('10'+['⁻⁸','⁻⁶','⁻⁴','⁻²','⁰'][i],xx-8,h-14);const zz=i*top/4;ctx.fillText((zz/1000).toFixed(0)+' km',4,y(zz)+3);}ctx.strokeStyle='#8ad3d0';ctx.lineWidth=2;ctx.beginPath();profile.rows.forEach((r,i)=>{if(i)ctx.lineTo(x(r.numberTotal_m3),y(r.z));else ctx.moveTo(x(r.numberTotal_m3),y(r.z));});ctx.stroke();const sy=y(profile.sounding.end_m);ctx.setLineDash([4,4]);ctx.strokeStyle='#edc986';ctx.beginPath();ctx.moveTo(54,sy);ctx.lineTo(w-15,sy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#edc986';ctx.fillText('Upper extension begins',Math.max(65,w-165),sy-7);$('profileNote').textContent='Sounding ends at '+km(profile.sounding.end_m)+'. Hydrostatic continuation reaches '+km(top)+' with a selected upper temperature of '+num(profile.upper.targetTemperature_K,1)+' K. Dashed line marks the join.';}
function row(label,value,cls=''){const tr=document.createElement('tr');for(const t of [label,value]){const td=document.createElement('td');td.textContent=t;if(t===value&&cls)td.className=cls;tr.append(td);}return tr;}
function change(){const {id,record:r,sky,profile:p}=active();$('scale').textContent=km(r.summary.surfaceScaleHeight_m);$('cloudBounds').textContent=(r.summary.cloudBase_m/1000).toFixed(2)+' → '+(r.summary.cloudTop_m/1000).toFixed(2)+' km';$('column').textContent=km(r.vertical.air_m);$('ozone').textContent=num(r.vertical.ozone_DU,0)+' DU';$('profileHash').textContent=r.profile_sha256;$('sourceHash').textContent='Clear-sky solver SHA-256: '+sky.solver_sha256;$('evLabel').textContent=(Number(exposure.value)>=0?'+':'')+exposure.value+' EV';skyDraw(sky);profileDraw(p,r);
 const maxCol=Math.max(...sky.column_validation.filter(x=>x.relative_to_scipy).flatMap(x=>x.relative_to_scipy)),maxJS=Math.max(...sky.column_validation.filter(x=>x.scipy).flatMap(x=>x.js.map((v,i)=>Math.abs(v-x.scipy[i])/Math.max(1,x.scipy[i])))),maxRay=Math.max(...sky.ray_convergence.map(x=>x.relativeSpectralL1));$('checks').replaceChildren(row('Column relative error · Gauss / SciPy',scientific(maxCol)),row('Column relative error · JavaScript / SciPy',scientific(maxJS)),row('Largest tested spectral L1 difference',pct(maxRay)),row('Radiance comparison',sky.budgets.viewSteps+' → '+sky.budgets.comparisonViewSteps+' view samples'),row('Physical accuracy of full sky','Open · single scattering only','open'));
 $('sensitivity').replaceChildren(...r.upperSensitivity.map(v=>row(v.options.top_m?'Domain top '+km(v.options.top_m):'Upper temperature '+v.options.upperTemperature_K+' K',(v.relativeVerticalChange>=0?'+':'')+pct(v.relativeVerticalChange,5))));window.a1AccuracyLab.currentId=id;}
function cloudDraw(){const mc=D.cloudMC,gpu=D.cloudGPU,{ctx,w,h}=fit($('cloudChart'));ctx.clearRect(0,0,w,h);axes(ctx,w,h,'Radiance per unit incident irradiance · sr⁻¹');const max=.13,plotW=w-74,step=plotW/mc.rays.length,base=h-33,y=v=>base-v/max*(h-66);for(let j=0;j<=4;j++){const v=j*max/4,yy=y(v);ctx.fillStyle='#acbcc7';ctx.font='10px system-ui';ctx.fillText(v.toFixed(3),4,yy+3);ctx.strokeStyle='#2c3d49';ctx.beginPath();ctx.moveTo(54,yy);ctx.lineTo(w-15,yy);ctx.stroke();}mc.rays.forEach((r,i)=>{for(const [j,key] of ['single','multiple'].entries()){const v=r[key],x=58+i*step+j*step*.35,bw=Math.max(2,step*.3);ctx.fillStyle=j?'#e6c28b':'#8ad3d0';ctx.fillRect(x,y(v.mean),bw,Math.max(1,base-y(v.mean)));ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(x+bw/2,y(v.mean+2*v.standard_error));ctx.lineTo(x+bw/2,y(Math.max(0,v.mean-2*v.standard_error)));ctx.stroke();}ctx.fillStyle='#acbcc7';ctx.fillText(String(i+1),58+i*step,base+18);});
 $('cloudChecks').replaceChildren(row('Paths per ray and scattering treatment',mc.samples_per_ray_per_order.toLocaleString()),row('Analytic / sampling checks',mc.analytic_tests.filter(x=>x.passed).length+' / '+mc.analytic_tests.length+' pass','status'),row('GPU / CPU voxel-sample difference',scientific(gpu.field_parity.maximum_absolute_extinction_error_m1)+' m⁻¹'),row('24-probe voxelization relative L1',pct(gpu.voxelization.sum_absolute_difference_over_sum_continuous,2),'open'),row('Unresolved Monte Carlo paths',String(mc.unresolved_paths),'status'));
 $('cloudRays').replaceChildren(...mc.rays.map((r,i)=>{const tr=document.createElement('tr');for(const t of [i+1,scientific(r.gpu_single_scatter),scientific(r.single.mean)+' ± '+scientific(r.single.standard_error),scientific(r.multiple.mean)+' ± '+scientific(r.multiple.standard_error),num(r.gpu_transmittance,5)]){const td=document.createElement('td');td.textContent=t;tr.append(td);}return tr;}));
 const f=D.cloudField,b=Uint8Array.from(atob(f.extinction_float32le),x=>x.charCodeAt(0)),dv=new DataView(b.buffer),[nx,ny,nz]=f.dimensions,{ctx:cx,w:ww,h:hh}=fit($('cloudSlice')),im=cx.createImageData(ww,hh),iz=Math.floor(nz/2);for(let y0=0;y0<hh;y0++)for(let x0=0;x0<ww;x0++){const ix=Math.round(x0/(ww-1)*(nx-1)),iy=Math.round((1-y0/(hh-1))*(ny-1)),e=dv.getFloat32(((iz*ny+iy)*nx+ix)*4,true),c=Math.round(255*(1-Math.exp(-e*450))),k=(y0*ww+x0)*4;im.data[k]=c;im.data[k+1]=c;im.data[k+2]=c;im.data[k+3]=255;}cx.putImageData(im,0,0);
}
function save(data,name,exact=false){const blob=new Blob([exact?data:JSON.stringify(data,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportProfile').onclick=()=>{const {id}=active();save(D.profileRaw[id],id+'.profile.json',true);};$('exportSky').onclick=()=>save(active().sky,active().id+'.sky.json');$('exportBenchmark').onclick=()=>save({gpu:D.cloudGPU,reference:D.cloudMC},'moon-fair-benchmark.json');
$('sky').onpointermove=e=>{const r=$('sky').getBoundingClientRect(),az=180*(e.clientX-r.left)/r.width,el=90*(1-(e.clientY-r.top)/r.height),c=interpolate(active().sky,el,az);$('hoverReadout').textContent='Elevation '+el.toFixed(1)+'° · azimuth '+az.toFixed(1)+'° · linear RGB ['+c.map(x=>x.toFixed(2)).join(', ')+'] · photopic luminance '+(c[0]*.2126+c[1]*.7152+c[2]*.0722).toFixed(2)+' cd/m²';};
window.a1AccuracyLab={ready:false,currentId:null,data:D,interpolate};world.onchange=regime.onchange=sun.onchange=exposure.oninput=change;let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(()=>{change();cloudDraw();},100);});change();cloudDraw();$('ready').textContent='Offline · 9 atmospheric states';window.a1AccuracyLab.ready=true;
})();
