(function(root){'use strict';const OM=root.OM=root.OM||{};
const DEPENDENCY={version:'0.180.0',git_blob:'ca4833532c363b72477b2e8a6f47cc0e2fc7b09a',url:'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.cjs'};
let source='';
function fromBase64(s){return new TextDecoder().decode(Uint8Array.from(atob(s),x=>x.charCodeAt(0)));}
function toBase64(s){const u=new TextEncoder().encode(s);let text='';for(let i=0;i<u.length;i+=32768)text+=String.fromCharCode(...u.subarray(i,i+32768));return btoa(text);}
async function verify(text){if(!root.crypto?.subtle)throw Error('A browser with Web Crypto support is required to verify the pinned Three.js library.');const bytes=new TextEncoder().encode(text),header=new TextEncoder().encode('blob '+bytes.length+'\0'),full=new Uint8Array(header.length+bytes.length);full.set(header);full.set(bytes,header.length);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-1',full))).map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==DEPENDENCY.git_blob)throw Error('The Three.js download does not match the pinned r180 source. No downloaded code was executed.');return true;}
OM.downloadBlob=function(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);};
OM.saveOffline=function(){if(!source){document.getElementById('boot-status').textContent='The library must finish loading before an offline copy can be saved.';return;}const doc=document.documentElement.cloneNode(true);doc.querySelector('#three-vendor').textContent=toBase64(source);doc.querySelector('#boot').removeAttribute('hidden');doc.querySelector('#boot-status').textContent='Opening the self-contained experience…';doc.querySelector('#runtime-error').setAttribute('hidden','');doc.querySelector('#help').removeAttribute('open');doc.querySelector('#panel').classList.remove('open');doc.querySelector('body').classList.remove('minimal');OM.downloadBlob(new Blob(['<!doctype html>\n'+doc.outerHTML],{type:'text/html'}),'Open_Moon_Shoreline_Offline.html');};
async function boot(){const status=document.getElementById('boot-status');try{
 const embedded=document.getElementById('three-vendor').textContent.trim();if(embedded){status.textContent='Verifying the embedded Three.js library…';source=fromBase64(embedded);}else{status.textContent='Loading pinned Three.js r180. Internet is needed for this first opening…';const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),18000);try{const r=await fetch(DEPENDENCY.url,{signal:ctrl.signal});if(!r.ok)throw Error('Three.js download returned HTTP '+r.status);source=await r.text();}finally{clearTimeout(timer);}}
 await verify(source);const m={exports:{}};new Function('module','exports',source+'\n//# sourceURL=three-r180.cjs')(m,m.exports);if(m.exports.REVISION!=='180')throw Error('Unexpected Three.js revision.');root.THREE=m.exports;status.textContent='Building the explorable shoreline…';await OM.boot(root.THREE);
 }catch(e){console.error(e);root.openMoonShorelineError=e.message;status.textContent=e.message;document.getElementById('boot-actions').hidden=false;document.getElementById('loader-bar').style.animation='none';}}
 OM.dependency=DEPENDENCY;OM.verifyVendor=verify;
 if(typeof document==='undefined'){if(typeof module!=='undefined')module.exports={DEPENDENCY,verify};return;}
 document.getElementById('retry').onclick=boot;document.getElementById('local-vendor').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const text=await f.text();await verify(text);document.getElementById('three-vendor').textContent=toBase64(text);await boot();}catch(err){document.getElementById('boot-status').textContent=err.message;}};
 document.getElementById('boot-about').onclick=()=>document.getElementById('help').showModal();
 document.getElementById('help-close').onclick=()=>document.getElementById('help').close();OM.dependency=DEPENDENCY;OM.verifyVendor=verify;boot();
})(globalThis);
