"""A sky tower on the Moon's highest ground: how the summit's wind bears on its height, how a frame that lets the
wind through stands up to it, and whether wind devices built into the frame would give useful power.

    OPENBLAS_NUM_THREADS=1 python -m research.studies.summit_tower.run   # results/summit_tower.json

It couples the geography atlas and drainage grids (the site and its lakes; kept out of Git, regenerated by
`python -m geography.atlas` and `python -m geography.drainage`), the climate products (the design run's winds at
the site from climate/gcm/site_winds.py, and the cloud-resolving equatorial ring), the illumination product
(sunlight at the ground, for a comparison with solar panels), the ecology register's fliers, and the engineering
tower models. Everything is closed-form sizing marched over a few thousand candidate frames and integrals over
wind distributions: light work, a few seconds on one core.
"""
from __future__ import annotations
import hashlib
import json
import sys
from pathlib import Path
import numpy as np

from atmosphere.radiative_convective.thermodynamics import EARTH, MOON
from engineering.towers import lattice as lt
from engineering.towers import wind_energy as we

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
SCHEMA = 'terluna.research.summit-tower/1'
ATLAS = ROOT / 'geography' / 'products' / 'atlas_28pct_4ppd.npz'
DRAINAGE_GRID = ROOT / 'geography' / 'products' / 'drainage_28pct_16ppd.npz'
DRAINAGE = ROOT / 'geography' / 'results' / 'drainage.json'
GCM_WINDS = ROOT / 'climate' / 'results' / 'gcm' / 'site_winds_A28_dim5_summit.json'
RING = ROOT / 'climate' / 'results' / 'crm' / 'ring_ring.json'
LIGHT = ROOT / 'illumination' / 'surface_light' / 'results' / 'surface_light.json'
ECOLOGY = ROOT / 'research' / 'studies' / 'lunar_cycle_ecology' / 'results' / 'lunar_cycle_ecology.json'

# The Lunar Orbiter Laser Altimeter's highest point (LROC; see sources.json): height above the mean radius.
LOLA_PEAK = dict(lat_deg=5.4125, lon_deg=-158.6335, height_above_mean_radius_m=10786.0)
TOWER_HEIGHTS_KM = (0.0, 2.5, 5.0, 10.0, 15.0, 20.0, 30.0)

# Design wind: the models' highest wind over the tower's heights, raised for what the models cannot show.
GUST_FACTOR = 1.4       # 3-second gust over a 3-hourly snapshot of 6-km columns
SUMMIT_SPEEDUP = 1.2    # flow over the summit's broad rise
RARITY_FACTOR = 1.2     # from two lunar days of ring to a return period of decades
EARTH_DESIGN_GUST = 50.0

HEIGHTS_M = np.array([1, 2, 3, 5, 7.5, 10, 15, 20, 30]) * 1e3
EARTH_HEIGHTS_M = np.array([1, 2, 3, 5, 7.5, 10]) * 1e3
BASE_SHARES = np.geomspace(1 / 80, 1 / 2, 30)
EXPONENTS = np.array([1.0, 1.5, 2.0, 3.0])
STEPS = 400
REFERENCE_HEIGHT_M = 10e3
FLOORS = lt.Floors()
FRAME = lt.Frame(top_width_m=round(FLOORS.full_width_m, -1))   # every layer holds the full floor programme

# Wind devices. Power coefficients on the frontal area, tip-speed ratios and speeds (sources.json): the fast rotor
# follows NREL's 5-MW reference turbine (peak 0.48 at 7.55; cut-in, rated and cut-out 3, 11.4 and 25 m/s); the slow
# rotor takes the top of FAO's 0.15-0.30 for American many-blade rotors at tip-speed ratio 1-1.5; the Savonius rotor
# FAO's 0.15 at 0.8-1; the bladeless mast a little below the 6% peak of Breen et al.'s wake-oscillator model, with
# the mean drag of an oscillating cylinder (Griffin). Rotors cut in at 3 m/s, where FAO's windpumps keep turning.
DEVICES = {
    'fast_rotor': we.Device('fast three-blade rotor (not safe for fliers)', 0.45, 3.0, 11.0, 25.0, 0.8, 0.1,
                            tip_speed_ratio=7.0, blades=3, chord_share=0.06, pitch_deg=5.0),
    'slow_rotor': we.Device('slow many-blade rotor', 0.30, 3.0, 8.0, 20.0, 0.9, 0.6,
                            tip_speed_ratio=1.0, blades=12, chord_share=0.12, pitch_deg=35.0),
    'savonius': we.Device('Savonius drag rotor on a vertical axis', 0.15, 3.0, 10.0, 25.0, 1.0, 1.2),
    'bladeless': we.Device('bladeless oscillating mast (vortex-induced vibration)', 0.05, 3.0, 8.0, 15.0, 2.0, 1.2),
}
SCREEN_FACTOR = 0.7        # power kept behind a mesh that keeps fliers out of a rotor
ARRAY_FACTOR = 0.8         # a porous tower face: some of the wind goes around it
DEVICE_COVERAGE = 0.5      # share of the frame's open face given to devices
DEVICE_ROTOR_RADIUS_M = {'fast_rotor': 40.0, 'slow_rotor': 10.0}
BUILDING_ENERGY_W_M2 = 100.0 * 1000.0 / 8766.0   # 100 kWh per m2 of floor per year, a low-energy building
CITY = dict(people=1_000_000, watts_each=2000.0) # an assumed city: one million people using 2 kW each on average
PANEL_EFFICIENCY = 0.22    # of the 202-1000 nm sunlight
CLAD_DRAG = 1.3            # a closed tower: drag coefficient on its full width
FLIERS = {'person_with_wings': dict(length_m=2.0, span_m=6.0, speed_m_s=6.0)}   # an assumed winged person
STORAGE_ROUND_TRIP = 0.8   # pumped storage, pump to turbine

# The central port, as the author chose it on 2026-09-27: long-haul sky ships dock in the named flight band
# (35-45 km above sea level, research/decisions.md), floors follow the frame (up to 100,000 m2 a storey, 2% of the
# frame's plan), and about 1.5 million people are present on a regular basis, in roughly this mix of uses.
FLIGHT_BAND_KM = (35.0, 45.0)
PORT_FLOORS = lt.Floors(area_per_storey_m2=100_000.0, plan_share=0.02)
PORT_ZONES_KM = ((0.0, 3.0, 'open public floors and terraces'), (3.0, 10.0, 'enclosed floors, air topped up'),
                 (10.0, 15.0, 'enclosed floors, air topped up'), (15.0, None, 'sealed, pressurised terminals and docks'))
PORT_OCCUPANCY = 1.5e6
# use: share of the floor, m2 of floor per person present (dense, roomy), share of capacity in use at a busy hour.
# The areas per person are rough planning figures from Earth practice, not yet checked against published standards.
PORT_USES = {
    'travel: terminals, docks, customs, lounges, ship servicing': (7.5 / 35, (30.0, 50.0), 0.8),
    'hotels': (7.0 / 35, (30.0, 45.0), 0.8),
    'short stay: compact and transit rooms': (3.0 / 35, (12.0, 20.0), 0.8),
    'commerce and trade': (7.0 / 35, (12.0, 20.0), 0.7),
    'shops, markets, food and drink': (4.0 / 35, (4.0, 8.0), 0.5),
    'events, conferences, leisure, observation': (3.5 / 35, (3.0, 6.0), 0.4),
    'services and back of house': (3.0 / 35, (50.0, 100.0), 0.8),
}
HOTEL_ROOM_M2, GUESTS_PER_ROOM, SHORT_STAY_BED_M2, HOURS_IN_PORT = 60.0, 1.6, 15.0, 2.0
PERSON = dict(mass_kg=80.0, drag_area_m2=0.7, canopy_drag_coefficient=1.3, landing_m_s=4.0)
NIGHT_HOURS = 354.4        # half a synodic month
FLUCTUATING_SWAY = 0.3     # gusts sway the top by about this share of the steady sway, roughly


def digest(path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()[:16]


def great_circle_km(lat1, lon1, lat2, lon2):
    la1, lo1, la2, lo2 = (np.radians(np.asarray(a, dtype=float)) for a in (lat1, lon1, lat2, lon2))
    c = np.sin(la1) * np.sin(la2) + np.cos(la1) * np.cos(la2) * np.cos(lo2 - lo1)
    return MOON.radius_m / 1e3 * np.arccos(np.clip(c, -1.0, 1.0))


def site() -> dict:
    """The summit cell of the atlas, the nearest rain-fed lakes and the LOLA peak."""
    a = np.load(ATLAS, allow_pickle=False)
    meta = json.loads(str(a['metadata']))
    h = a['height_m']
    i, j = np.unravel_index(np.argmax(h), h.shape)
    lat, lon = float(a['lat_deg'][i]), float(a['lon_deg'][j])
    sea = float(meta['sea_level_m'])
    g = np.load(DRAINAGE_GRID, allow_pickle=False)
    grid = json.loads(str(g['metadata']))['grid']
    cells, level = g['lake_cell'], g['lake_level_m']
    ppd = grid['pixels_per_degree']
    row, col = cells // grid['cols'], cells % grid['cols']
    clat = 90.0 - (row + 0.5) / ppd
    clon = (col + 0.5) / ppd
    dist = great_circle_km(lat, lon, clat, clon)
    lakes = json.loads(DRAINAGE.read_text())['lakes']['largest']
    near = []
    for lake in lakes:
        c = great_circle_km(lat, lon, lake['centre'][0], lake['centre'][1])
        if c < 1200.0:
            same = np.abs(level - lake['level_above_sea_m'] - sea) < 1.0
            shore = float(dist[same].min()) if same.any() else None
            near.append(dict(centre=lake['centre'], area_km2=lake['area_km2'], level_above_sea_m=lake['level_above_sea_m'],
                             max_depth_m=lake['max_depth_m'], centre_km=round(float(c)), shore_km=None if shore is None else round(shore),
                             summit_above_lake_m=round(float(h[i, j]) - sea - lake['level_above_sea_m'])))
    LA, LO = np.meshgrid(a['lat_deg'], a['lon_deg'], indexing='ij')
    around = great_circle_km(lat, lon, LA, LO)
    rise = {f'median_ground_within_{r}_km_above_sea_m': round(float(np.median(h[around < r])) - sea) for r in (100, 300)}
    return dict(lat_deg=lat, lon_deg=lon, ground_above_geoid_m=round(float(h[i, j])), ground_above_sea_m=round(float(h[i, j]) - sea),
                sea_level_m=sea, grid='atlas 4 px/deg (7.6 km)', lola_peak=LOLA_PEAK, **rise,
                nearest_lake_shore_km=round(float(dist.min())),
                lakes=sorted(near, key=lambda d: d['centre_km']))


def air(gcm: dict, ground_above_sea_m: float):
    """Air density (kg/m3) as a function of height above the summit ground, from the design run's column at the
    site (heights above the model ground plus the model ground's height), interpolated in log density."""
    z_sea = np.asarray(gcm['height_m']) + gcm['ground_height_m']
    log_rho = np.log(np.asarray(gcm['density_kg_m3']))
    return lambda z: np.exp(np.interp(ground_above_sea_m + np.asarray(z, dtype=float), z_sea, log_rho))


def earth_air(z):
    """The International Standard Atmosphere's density (kg/m3) up to 32 km."""
    z = np.asarray(z, dtype=float)
    g0, R = 9.80665, 287.05287
    t = np.where(z < 11e3, 288.15 - 0.0065 * z, np.where(z < 20e3, 216.65, 216.65 + 0.001 * (z - 20e3)))
    p11 = 101325.0 * (216.65 / 288.15) ** (g0 / (R * 0.0065))
    p20 = p11 * np.exp(-g0 * 9e3 / (R * 216.65))
    p = np.where(z < 11e3, 101325.0 * (t / 288.15) ** (g0 / (R * 0.0065)),
                 np.where(z < 20e3, p11 * np.exp(-g0 * (z - 11e3) / (R * 216.65)),
                          p20 * (t / 216.65) ** (-g0 / (R * 0.001))))
    return p / (R * t)


def wind_climate(gcm: dict, ring: dict, ground_above_sea_m: float) -> list:
    """The wind over the tower's heights from the two models: the design run's 3-day means (both components) at the
    height above its own ground, and the cloud-resolving ring's 3-hourly east-west wind at the height above sea
    level. The ring's distribution is fitted with a Weibull law and its scale raised by the cube root of the design
    run's ratio of the speed's mean cube to the east-west component's, for the north-south wind the ring lacks."""
    gz = np.asarray(gcm['height_m']) + gcm['ground_height_m']
    rz = np.array([float(k.split('_')[0]) * 1e3 for k in ring['wind_aloft_m_s']])
    rstat = lambda key: np.array([v[key] for v in ring['wind_aloft_m_s'].values()])
    rho = air(gcm, ground_above_sea_m)
    rows = []
    for zk in TOWER_HEIGHTS_KM:
        zs = ground_above_sea_m + zk * 1e3
        gi = lambda key: float(np.interp(zs, gz, np.asarray(gcm[key])))
        ri = lambda key: float(np.interp(zs, rz, rstat(key)))
        k, c = we.weibull_from_percentiles(ri('median'), ri('p90'))
        c_full = c * (gi('mean_cube_m3_s3') / gi('mean_cube_u_m3_s3')) ** (1.0 / 3.0)
        d = float(rho(zk * 1e3))
        rows.append(dict(height_above_ground_km=zk, height_above_sea_km=round(zs / 1e3, 2), density_kg_m3=round(d, 3),
                         gcm_3day=dict(median=round(gi('speed_p50_m_s'), 2), p99=round(gi('speed_p99_m_s'), 2),
                                       max=round(gi('speed_max_m_s'), 2), return_50yr=round(gi('return_50yr_m_s'), 2),
                                       steadiness=round(gi('steadiness'), 2),
                                       resource_w_m2=round(0.5 * d * gi('mean_cube_m3_s3'), 1)),
                         ring_3hourly=dict(median=round(ri('median'), 2), p90=round(ri('p90'), 2), p99=round(ri('p99'), 2),
                                           max=round(ri('max'), 2)),
                         weibull=dict(shape=round(k, 3), scale_east_west=round(c, 3), scale_with_north_south=round(c_full, 3),
                                      p99_check=round(we.weibull_quantile(k, c, 0.99), 2)),
                         resource_w_m2=round(we.resource_w_m2(k, c_full, d), 1)))
    return rows


def design_winds(climate: list, tower_top_km: float) -> dict:
    span = [r for r in climate if r['height_above_ground_km'] <= tower_top_km]
    highest = max(max(r['ring_3hourly']['max'], r['gcm_3day']['max']) for r in span)
    model_based = highest * GUST_FACTOR * SUMMIT_SPEEDUP * RARITY_FACTOR
    return dict(models_highest_m_s=round(highest, 1), service_gust_m_s=round(highest * GUST_FACTOR, 1),
                model_based_design_gust_m_s=round(model_based, 1),
                factors=dict(gust=GUST_FACTOR, summit_speedup=SUMMIT_SPEEDUP, rarity=RARITY_FACTOR),
                scenarios_m_s=[0.0, round(highest, 1), round(model_based, 1), EARTH_DESIGN_GUST])


def scan(world: lt.World, heights, winds, frame=FRAME, floors=FLOORS, added_drag=0.0) -> dict:
    """Every candidate frame (base width share, flare) for each height and design gust; bases narrower than the
    frame's top are left out."""
    H, share, p, V = np.meshgrid(heights, BASE_SHARES, EXPONENTS, winds, indexing='ij')
    keep = H * share >= frame.top_width_m
    H, share, p, V = H[keep], share[keep], p[keep], V[keep]
    r = lt.size(H, H * share, p, V, world, frame, floors, steps=STEPS, added_drag=added_drag)
    r['label'] = np.array([f'{h:.0f}|{v:.1f}' for h, v in zip(r['height_m'], r['design_wind_m_s'])])
    return r


def pick(r: dict, service_gust: float) -> dict:
    out = {}
    for label, idx in lt.lightest(r, r['label'], service_gust):
        if idx is None:
            out[label] = None
            continue
        out[label] = {k: float(v[idx]) for k, v in r.items() if k != 'label'}
        out[label]['sway_at_service_m'] = out[label]['sway_per_wind2_m'] * service_gust ** 2
    return out


def summarise(choice: dict | None) -> dict | None:
    if choice is None:
        return None
    return dict(height_km=round(choice['height_m'] / 1e3, 2), design_gust_m_s=choice['design_wind_m_s'],
                base_width_m=round(choice['base_width_m']), flare_exponent=choice['exponent'],
                frame_mass_mt=round(choice['frame_mass_kg'] / 1e9, 3), floor_mass_mt=round(choice['floor_mass_kg'] / 1e9, 3),
                floor_area_km2=round(choice['floor_area_m2'] / 1e6, 2), frequency_hz=round(choice['frequency_hz'], 4),
                period_s=round(1.0 / choice['frequency_hz'], 1), sway_at_service_m=round(choice['sway_at_service_m'], 2),
                buckling_factor=round(choice['buckling_factor'], 1),
                footing_area_m2_at_1mpa=round(choice['base_leg_force_n'] / 1e6))


def profile(choice: dict, n=200):
    H, b0, p = choice['height_m'], choice['base_width_m'], choice['exponent']
    bt = min(FRAME.top_width_m, b0)
    z = (np.arange(n) + 0.5) / n * H
    return z, bt + (b0 - bt) * (1.0 - z / H) ** p, H / n


def energy(choice: dict, climate: list, rho, floors=FLOORS, coverage=DEVICE_COVERAGE, speedup=1.0) -> dict:
    """Mean output of each kind of device filling `coverage` of the frame's open face, against the tower's own use
    and a city's; `speedup` raises every wind speed by that factor (the flow over the summit)."""
    z, b, dz = profile(choice)
    open_share = 1.0 - floors.band_height_m / floors.spacing_m
    area = coverage * open_share * b * dz
    hk = np.array([r['height_above_ground_km'] for r in climate]) * 1e3
    shape = np.interp(z, hk, [r['weibull']['shape'] for r in climate])
    scale = speedup * np.interp(z, hk, [r['weibull']['scale_with_north_south'] for r in climate])
    dens = rho(z)
    demand = choice['floor_area_m2'] * BUILDING_ENERGY_W_M2
    resource = float(sum(a * we.resource_w_m2(k, c, d) for a, k, c, d in zip(area, shape, scale, dens)))
    out = dict(device_area_km2=round(float(area.sum()) / 1e6, 3), resource_mw=round(resource / 1e6, 2),
               betz_limit_mw=round(resource * 16.0 / 27.0 / 1e6, 1),
               tower_demand_mw=round(demand / 1e6), city_demand_mw=round(CITY['people'] * CITY['watts_each'] / 1e6),
               devices={})
    for key, dev in DEVICES.items():
        screens = SCREEN_FACTOR if key in ('slow_rotor', 'savonius') else 1.0
        watts = sum(a * we.mean_output_w_m2(dev, k, c, d, screens) for a, k, c, d in zip(area, shape, scale, dens)) * ARRAY_FACTOR
        mid = len(z) // 2
        out['devices'][key] = dict(name=dev.name, screened=screens < 1.0, mean_mw=round(watts / 1e6, 2),
                                   w_per_m2=round(watts / float(area.sum()), 2),
                                   share_of_tower_use=round(watts / demand, 4),
                                   share_of_city_use=round(watts / (CITY['people'] * CITY['watts_each']), 5),
                                   turning_share_mid_height=round(we.working_share(dev, shape[mid], scale[mid]), 3))
    return out


def sunlight(albedo=0.1) -> dict:
    """Mean sunlight (202-1000 nm) over the lunar cycle at the equator on a horizontal panel and on a vertical panel
    facing east (or west), from the design case's clear-sky spectra at sea level; and a panel's mean output."""
    d = json.loads(LIGHT.read_text())
    case = d['cases']['moon_1.2atm/design']
    R = np.asarray(d['columns']['moon_1.2atm']['reflectance_from_below'])
    elev = np.array(sorted(float(e) for e in case['spectra']))
    glob, direct = [], []
    for e in elev:
        s = case['spectra'][f'{e:.1f}' if f'{e:.1f}' in case['spectra'] else str(e)]
        dirh = np.asarray(s['direct_w_m2_nm'])
        down = (dirh + np.asarray(s['diffuse_black_w_m2_nm'])) / (1.0 - albedo * R)
        glob.append(down.sum())
        direct.append(dirh.sum())
    elev = np.concatenate([[0.0], elev])
    glob = np.concatenate([[0.0], glob])
    direct = np.concatenate([[0.0], direct])
    diffuse = glob - direct
    grid = np.linspace(0.0, 90.0, 901)
    g = np.interp(grid, elev, glob)
    dh = np.interp(grid, elev, direct)
    df = np.interp(grid, elev, diffuse)
    beam_on_wall = np.where(grid > 0.5, dh / np.tan(np.radians(np.maximum(grid, 0.5))), 0.0)
    horizontal = 2.0 * np.trapezoid(g, grid) / 360.0
    # East wall: the morning's beam plus half the sky's diffuse and half the ground's reflection, all day long.
    wall = (np.trapezoid(beam_on_wall, grid) + 2.0 * np.trapezoid(0.5 * df + 0.5 * albedo * g, grid)) / 360.0
    return dict(band_nm=[202, 1000], horizontal_mean_w_m2=round(float(horizontal), 1), east_wall_mean_w_m2=round(float(wall), 1),
                panel_efficiency=PANEL_EFFICIENCY, horizontal_panel_w_m2=round(float(horizontal) * PANEL_EFFICIENCY, 1),
                east_wall_panel_w_m2=round(float(wall) * PANEL_EFFICIENCY, 1), noon_global_w_m2=round(float(glob[-1]), 1))


def loads(choice: dict, world: lt.World, service_gust: float, floors=FLOORS) -> dict:
    """What the design gust asks of the frame when devices fill half its openings (stopped for the storm) and when
    the tower is closed like a building: the base moment against the open frame's for the same outline, and the
    lightest frame of that height meeting the checks; and the moment while devices turn in the service gust."""
    z, b, dz = profile(choice)
    rho = world.air_density(z)
    fr = FRAME
    V = choice['design_wind_m_s']
    open_share = 1.0 - floors.band_height_m / floors.spacing_m
    frame_c = fr.force_coefficient() * fr.solidity + floors.drag_coefficient * floors.band_height_m / floors.spacing_m
    moment = lambda c, wind: float((0.5 * rho * 1.2 * wind * wind * c * b * z * dz).sum())
    base = moment(frame_c, V)
    stopped = {f'{k}_stopped': frame_c + DEVICES[k].parked_drag_coefficient * DEVICE_COVERAGE * open_share
               for k in ('slow_rotor', 'bladeless')}
    out = {}
    for name, c in {'open_frame': frame_c, **stopped, 'closed_tower': CLAD_DRAG}.items():
        best = pick(scan(world, [choice['height_m']], [V], floors=floors, added_drag=c - frame_c), service_gust)
        best = summarise(next(iter(best.values())))
        out[name] = dict(drag_per_width=round(c, 3), base_moment_ratio_same_outline=round(moment(c, V) / base, 2),
                         lightest_frame=best)
    for k in ('slow_rotor', 'bladeless'):
        c = frame_c + DEVICES[k].thrust_coefficient * DEVICE_COVERAGE * open_share
        out[f'{k}_turning_in_service_gust'] = dict(drag_per_width=round(c, 3),
                                                   base_moment_ratio_same_outline=round(moment(c, service_gust) / base, 2))
    return out


def collisions(ecology: dict, wind_m_s=4.0) -> dict:
    """Band's single-crossing collision probability for the register's fliers and a winged person, crossing
    downwind through a slow and a fast rotor turning in a wind of wind_m_s."""
    moon = ecology['flight']['fliers']
    fliers = {'moth_0.33g': dict(length_m=0.02, span_m=0.04, speed_m_s=float(np.mean(moon['moth_0.33g']['airspeed_m_s']['moon']))),
              'bird_100g': dict(length_m=0.20, span_m=0.35, speed_m_s=float(np.mean(moon['bird_100g']['airspeed_m_s']['moon']))),
              **FLIERS}
    out = {key: {name: round(we.band_collision_probability(DEVICES[key], DEVICE_ROTOR_RADIUS_M[key], wind_m_s,
                                                           f['length_m'], f['span_m'], f['speed_m_s']), 3)
                 for name, f in fliers.items()}
           for key in ('slow_rotor', 'fast_rotor')}
    tips = {key: round(DEVICES[key].tip_speed_ratio * wind_m_s, 1) for key in out}
    return dict(wind_m_s=wind_m_s, fliers={k: {kk: round(vv, 3) for kk, vv in v.items()} for k, v in fliers.items()},
                rotor_radius_m=DEVICE_ROTOR_RADIUS_M, tip_speed_m_s=tips, probability_per_crossing=out)


def night_storage(site_info: dict, demands_mw: dict) -> dict:
    """Water to lift from the Korolev lake to the summit during the day to carry a demand through the night: the
    head is the summit ground above the lake's surface."""
    lake = next(l for l in site_info['lakes'] if abs(l['centre'][0] + 4.33) < 0.5 and abs(l['centre'][1] + 157.69) < 0.5)
    head = lake['summit_above_lake_m']
    per_m3 = 1000.0 * MOON.surface_gravity * head * STORAGE_ROUND_TRIP / 3.6e6
    return dict(lake_centre=lake['centre'], head_m=head, shore_km=lake['shore_km'], round_trip=STORAGE_ROUND_TRIP,
                delivered_kwh_per_m3=round(per_m3, 2), night_hours=NIGHT_HOURS,
                water_mm3={k: round(mw * 1e3 * NIGHT_HOURS / per_m3 / 1e6, 1) for k, mw in demands_mw.items()})


def air_at(gcm: dict, height_above_sea_m: float) -> dict:
    """Mean pressure, temperature and density of the design run's air at the site, and the height on Earth whose
    oxygen partial pressure matches (International Standard Atmosphere troposphere)."""
    z = np.asarray(gcm['height_m']) + gcm['ground_height_m']
    p = float(np.exp(np.interp(height_above_sea_m, z, np.log(gcm['pressure_pa']))))
    t = float(np.interp(height_above_sea_m, z, gcm['temperature_k']))
    rho = float(np.exp(np.interp(height_above_sea_m, z, np.log(gcm['density_kg_m3']))))
    from atmosphere.radiative_convective.thermodynamics import earthlike_air
    o2 = earthlike_air(gcm['configuration']['pressure_pa'], 400.0).fractions['O2']
    earth_p = o2 * p / 0.2095
    earth_m = (1.0 - (earth_p / 101325.0) ** (1.0 / 5.25588)) / 2.25577e-5
    return dict(pressure_atm=round(p / 101325.0, 3), temperature_c=round(t - 273.15, 1), density_kg_m3=round(rho, 3),
                oxygen_like_earth_at_m=round(earth_m, -1))


def port(gcm: dict, site_info: dict, climate: list, world: lt.World, winds: dict, light: dict) -> dict:
    """The central port: its frame, floors and air by zone, programme and occupancy, power and evacuation."""
    ground = site_info['ground_above_sea_m']
    H = float(np.ceil((FLIGHT_BAND_KM[0] * 1e3 - ground) / 1e3) * 1e3)
    V, service = winds['model_based_design_gust_m_s'], winds['service_gust_m_s']
    choice = next(iter(pick(scan(world, [H], [V], floors=PORT_FLOORS), service).values()))
    z, b, dz = profile(choice)
    per_m = PORT_FLOORS.area_per_m(b)
    zones = []
    for lo, hi, use in PORT_ZONES_KM:
        top = H if hi is None else hi * 1e3
        inside = (z >= lo * 1e3) & (z < top)
        zones.append(dict(from_km=lo, to_km=round(top / 1e3, 1), use=use,
                          floor_km2=round(float(per_m[inside].sum() * dz) / 1e6, 1),
                          width_km=[round(float(np.interp(lo * 1e3, z, b)) / 1e3, 2), round(float(np.interp(top, z, b)) / 1e3, 2)],
                          air_at_bottom=air_at(gcm, ground + lo * 1e3), air_at_top=air_at(gcm, ground + top)))
    floor = choice['floor_area_m2']
    uses, busy, full = {}, np.zeros(2), np.zeros(2)
    for name, (share, (dense, roomy), present) in PORT_USES.items():
        area = share * floor
        cap = np.array([area / roomy, area / dense])
        uses[name] = dict(floor_km2=round(area / 1e6, 2), m2_per_person=[dense, roomy],
                          present_at_busy_hour=[round(float(v), -3) for v in cap * present])
        busy += cap * present
        full += cap
    hotel = PORT_USES['hotels'][0] * floor / HOTEL_ROOM_M2
    beds = PORT_USES['short stay: compact and transit rooms'][0] * floor / SHORT_STAY_BED_M2
    travel = uses['travel: terminals, docks, customs, lounges, ship servicing']['present_at_busy_hour']
    power = {f'{label}': energy(choice, climate, world.air_density, PORT_FLOORS, coverage, speedup)
             for label, coverage, speedup in (('half_face', 0.5, 1.0), ('whole_face', 1.0, 1.0),
                                               ('whole_face_summit_speedup', 1.0, SUMMIT_SPEEDUP))}
    demand = power['whole_face']['tower_demand_mw']
    open_share = 1.0 - PORT_FLOORS.band_height_m / PORT_FLOORS.spacing_m
    steel = {}
    slow = DEVICES['slow_rotor'].parked_drag_coefficient
    for label, cd, cover in (('open_frame', 0.0, 0.0), ('louvers_edge_on_half_face', 0.15, 0.5),
                             ('solid_panels_half_face', CLAD_DRAG, 0.5), ('slow_rotors_stopped_half_face', slow, 0.5),
                             ('slow_rotors_stopped_whole_face', slow, 1.0)):
        best = next(iter(pick(scan(world, [H], [V], floors=PORT_FLOORS, added_drag=cd * cover * open_share), service).values()))
        steel[label] = None if best is None else round(best['frame_mass_kg'] / 1e9, 1)
    canopy = {}
    for label, height in (('base', 0.0), ('top', H)):
        rho = float(world.air_density(height))
        g = world.gravity_m_s2
        canopy[label] = dict(density_kg_m3=round(rho, 3),
                             free_fall_m_s=round(float(np.sqrt(2 * PERSON['mass_kg'] * g / (rho * PERSON['drag_area_m2']))), 1),
                             canopy_across_m=round(float(np.sqrt(4 / np.pi * 2 * PERSON['mass_kg'] * g /
                                                                 (rho * PERSON['canopy_drag_coefficient'] * PERSON['landing_m_s'] ** 2))), 1))
    return dict(
        height_km=H / 1e3, top_above_sea_km=round((ground + H) / 1e3, 1), flight_band_km=list(FLIGHT_BAND_KM),
        design=summarise(choice), width_profile='width = 320 m + (base - 320 m) x (1 - z/H)^p',
        zones=zones, floor_km2=round(floor / 1e6, 1),
        occupancy=dict(regular_present=PORT_OCCUPANCY, busy_hour_range=[round(float(v), -4) for v in busy],
                       all_full_range=[round(float(v), -4) for v in full], uses=uses,
                       hotel_rooms=round(hotel, -3), hotel_guests=round(hotel * GUESTS_PER_ROOM, -3),
                       short_stay_beds=round(beds, -3), travellers_present=travel,
                       passengers_per_hour=[round(v / HOURS_IN_PORT, -3) for v in travel]),
        power=dict(tower_use_mw=demand, wind=power,
                   ground_panels_km2_for_tower=round(demand * 1e6 / light['horizontal_panel_w_m2'] / 1e6, 1),
                   frame_steel_mt=steel,
                   night_storage=night_storage(site_info, dict(tower=demand))),
        evacuation=dict(person=PERSON, canopy=canopy,
                        descent_minutes={f'from_{k}_km': round(k * 1e3 / PERSON['landing_m_s'] / 60.0)
                                         for k in (3, 10, int(H / 1e3))}))


def results() -> dict:
    gcm = json.loads(GCM_WINDS.read_text())
    ring = json.loads(RING.read_text())
    ecology = json.loads(ECOLOGY.read_text())
    s = site()
    rho = air(gcm, s['ground_above_sea_m'])
    moon = lt.World('moon', MOON.surface_gravity, rho)
    earth = lt.World('earth', EARTH.surface_gravity, earth_air)
    climate = wind_climate(gcm, ring, s['ground_above_sea_m'])
    winds = design_winds(climate, REFERENCE_HEIGHT_M / 1e3)
    service = winds['service_gust_m_s']
    moon_scan = pick(scan(moon, HEIGHTS_M, winds['scenarios_m_s']), service)
    earth_scan = pick(scan(earth, EARTH_HEIGHTS_M, [0.0, EARTH_DESIGN_GUST]), service)
    bare = pick(scan(moon, HEIGHTS_M, [winds['model_based_design_gust_m_s']], floors=None), service)
    carbon = pick(scan(moon, HEIGHTS_M, [winds['model_based_design_gust_m_s']], frame=lt.Frame(material=lt.CARBON, top_width_m=FRAME.top_width_m)), service)
    ref_label = f"{REFERENCE_HEIGHT_M:.0f}|{winds['model_based_design_gust_m_s']:.1f}"
    ref = moon_scan[ref_label]
    by_height = {}
    for H in HEIGHTS_M:
        row = {}
        for V in winds['scenarios_m_s']:
            row[f'{V:g}'] = summarise(moon_scan.get(f'{H:.0f}|{V:.1f}'))
        row['bare_frame'] = summarise(bare.get(f"{H:.0f}|{winds['model_based_design_gust_m_s']:.1f}"))
        row['carbon_frame'] = summarise(carbon.get(f"{H:.0f}|{winds['model_based_design_gust_m_s']:.1f}"))
        by_height[f'{H / 1e3:g}_km'] = row
    earth_rows = {f'{H / 1e3:g}_km': {f'{V:g}': summarise(earth_scan.get(f'{H:.0f}|{V:.1f}')) for V in (0.0, EARTH_DESIGN_GUST)}
                  for H in EARTH_HEIGHTS_M}
    vortex = ref['frequency_hz'] * ref['width_two_thirds_m'] / 0.12
    top_air = dict(density_kg_m3=round(float(rho(REFERENCE_HEIGHT_M)), 3), ground_density_kg_m3=round(float(rho(0.0)), 3))
    return dict(
        site=s, air_at_reference=top_air, wind=climate, design_winds=winds,
        materials={k: dict(name=m.name, allowable_mpa=round(lt.Frame(material=m).allowable_pa / 1e6),
                           self_weight_length_km_moon=round(lt.Frame(material=m).allowable_pa / (m.density_kg_m3 * MOON.surface_gravity) / 1e3, 1),
                           self_weight_length_km_earth=round(lt.Frame(material=m).allowable_pa / (m.density_kg_m3 * EARTH.surface_gravity) / 1e3, 1))
                   for k, m in (('steel', lt.STEEL), ('carbon', lt.CARBON))},
        frame=dict(solidity=FRAME.solidity, force_coefficient=round(FRAME.force_coefficient(), 3), top_width_m=FRAME.top_width_m,
                   floors=dict(spacing_m=FLOORS.spacing_m, storeys=FLOORS.storeys, area_per_storey_m2=FLOORS.area_per_storey_m2,
                               floor_area_km2_per_km=round(FLOORS.area_per_m(FRAME.top_width_m) * 1e3 / 1e6, 3),
                               mass_per_area_kg_m2=FLOORS.mass_per_area_kg_m2)),
        moon=by_height, earth=earth_rows,
        reference=dict(summary=summarise(ref), frontal_area_km2=round(ref['frontal_area_m2'] / 1e6, 2),
                       vortex_lock_in_wind_m_s=round(vortex, 1),
                       top_acceleration_rough_m_s2=round((2.0 * np.pi * ref['frequency_hz']) ** 2 * FLUCTUATING_SWAY
                                                          * ref['sway_per_wind2_m'] * service ** 2, 4),
                       base_leg_force_from_wind_share=round(ref['base_moment_nm'] / (np.sqrt(2.0) * ref['base_width_m'])
                                                            / ref['base_leg_force_n'], 3)),
        energy=(power := energy(ref, climate, rho)), sunlight=(light := sunlight()), loads=loads(ref, moon, service),
        tower_panels=dict(area_km2=round(DEVICE_COVERAGE * 2.0 * ref['frontal_area_m2'] / 1e6, 2),
                          mean_mw=round(DEVICE_COVERAGE * 2.0 * ref['frontal_area_m2'] * light['east_wall_panel_w_m2'] / 1e6, 1),
                          note='panels on half of the east and west faces; all of it by day',
                          city_horizontal_panels_km2=round(power['city_demand_mw'] * 1e6 / light['horizontal_panel_w_m2'] / 1e6, 1)),
        collisions=collisions(ecology),
        night_storage=night_storage(s, dict(tower=power['tower_demand_mw'], city=power['city_demand_mw'])),
        port=port(gcm, s, climate, moon, winds, light))


def main() -> int:
    r = results()
    files = {p: digest(ROOT / p) for p in ('research/studies/summit_tower/run.py', 'engineering/towers/lattice.py',
                                           'engineering/towers/wind_energy.py')}
    inputs = {str(p.relative_to(ROOT)): digest(p) for p in (GCM_WINDS, RING, DRAINAGE, LIGHT, ECOLOGY)}
    inputs['geography/products/atlas_28pct_4ppd.npz'] = digest(ATLAS)
    inputs['geography/products/drainage_28pct_16ppd.npz'] = digest(DRAINAGE_GRID)
    product = dict(schema=SCHEMA, producer=dict(study='summit_tower', files=files, inputs=inputs),
                   evidence=('First-order concept sizing and screening arithmetic. The winds are two models\' '
                             '(3-day GCM means with T21 terrain and a two-dimensional cloud-resolving ring over two '
                             'lunar days), raised by stated factors for gusts, the summit and rarity; the frames are '
                             'sized by closed-form statics with one member-buckling factor and one gust factor; device '
                             'coefficients come from Earth devices. Nothing here is a structural design.'),
                   reading_rule=('Heights of the tower are above the summit ground; wind heights also above sea '
                                 'level. Masses in megatonnes (Mt = 1e9 kg). moon[height][design gust] is the lightest '
                                 'frame meeting the checks (sway within 1/500 of the height under the service gust, '
                                 'whole-frame buckling factor at least 3, base no wider than half the height), or null '
                                 'if none does. Energy in MW is a mean over all winds.'), **r)
    out = HERE / 'results' / 'summit_tower.json'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(product, indent=1) + '\n')
    print(out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
