const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../src/core.js');const close=(a,b,tol=1e-9)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
test('Sun follows a continuous normalized full-cycle path',()=>{for(let i=0;i<=1000;i++){const s=C.sunAt(i/1000);close(s.x*s.x+s.y*s.y+s.z*s.z,1);}});
test('Noon, sunset, midnight, sunrise have expected positions',()=>{close(C.sunAt(0).elevation,90);close(C.sunAt(.25).elevation,0);close(C.sunAt(.5).elevation,-90);close(C.sunAt(.75).elevation,0);});
test('Sun phase wraps both directions',()=>{close(C.sunAt(-.25).x,-1);close(C.sunAt(1.25).x,1);});
test('Solar elevation inverses preserve dawn and dusk branches',()=>{for(let a=-90;a<=90;a+=5){for(const rising of[false,true])close(C.sunAt(C.phaseForElevation(a,rising)).elevation,a,1e-6);}});
test('The lunar clock has the expected period',()=>close(C.PERIOD/C.DAY,29.53059));
test('Calibrated vertical field of view uses actual viewing geometry',()=>close(C.calibratedFov(30,65),2*Math.atan(15/65)*180/Math.PI));
test('Calibration rejects invalid input',()=>assert.throws(()=>C.calibratedFov(0,50)));
test('Cloud optical depth has the correct dimensions and value',()=>close(C.cloudTau(.1,1000,10),15));
test('Cloud optical depth responds correctly to droplet radius',()=>close(C.cloudTau(.1,1000,20),7.5));
test('Cloud data rejects negative water content',()=>assert.throws(()=>C.cloudTau(-1,1000,10)));
test('Weather episode is bounded and finite',()=>{for(let t=-100;t<=15000;t+=13){const w=C.weatherAt(t);assert.ok(w.rain>=0&&w.rain<=10);assert.ok(w.coverage>=0&&w.coverage<=1);assert.ok(w.humidity>0&&w.humidity<=1);assert.ok(Object.values(w).every(Number.isFinite));}});
test('Episode forcing is continuous at keyframe boundaries',()=>{for(const a of C.EPISODE.slice(1,-1)){const x=C.weatherAt(a[0]-.001),y=C.weatherAt(a[0]+.001);for(const k of Object.keys(x))close(x[k],y[k],1e-4);}});
test('Clear forcing does not inherit a rain episode',()=>close(C.weatherAt(8000,'clear').rain,0));
test('Fog has prescribed low visibility and no rain',()=>{const w=C.weatherAt(8000,'fog');close(w.visibility,110);close(w.rain,0);});
test('Reservoir zero-rate branch preserves inflow',()=>{const r=C.reservoirStep(.2,.01,0,0,2,10);close(r.storage,.3);close(r.residual,0);});
test('Reservoir overflow is explicitly recorded',()=>{const r=C.reservoirStep(.8,.1,0,0,1,10);close(r.storage,1);close(r.overflow,.8);close(r.residual,0);});
test('Reservoir exponential drying matches its analytic solution',()=>{const r=C.reservoirStep(1,0,.01,.02,2,10);close(r.storage,Math.exp(-.3));close(r.residual,0);});
test('Capped reservoir conserves water across boundary contact',()=>{const r=C.reservoirStep(.1,.3,.01,.02,.5,15);close(r.storage,.5);assert.ok(r.overflow>0);close(r.residual,0);});
test('Boundary-start reservoir can drain below capacity',()=>{const r=C.reservoirStep(1,0,.01,.02,1,10);assert.ok(r.storage<1);close(r.residual,0);});
test('Invalid water data fails immediately',()=>assert.throws(()=>C.reservoirStep(3,1,0,0,1,10)));
test('Reservoir subdivision is exact for constant forcing',()=>{let s=.2;for(let i=0;i<100;i++)s=C.reservoirStep(s,.014,.001,.002,1,2).storage;close(s,C.reservoirStep(.2,.014,.001,.002,1,200).storage,1e-12);});
test('Water ledger conserves exposure plus canopy column water',()=>{for(let t=0;t<=14400;t+=300){const l=C.ledgerAt(t);assert.ok(Math.abs(l.residual)<1e-9);assert.ok(l.exposed>=0&&l.exposed<=2);assert.ok(l.canopy>=0&&l.canopy<=1.4);assert.ok(l.leaf>=0&&l.leaf<=.35);}});
test('Sheltered ground remains dry through the rain',()=>close(C.ledgerAt(14400).sheltered,0));
test('Clearing sky leaves persistent surface water',()=>{const l=C.ledgerAt(14400);assert.equal(C.weatherAt(14400).rain,0);assert.ok(l.exposed>.05&&l.canopy>.05);});
test('Replay produces identical weather-water state',()=>assert.deepEqual(C.ledgerAt(8210),C.ledgerAt(8210)));
test('Two-second and ten-second water steps are close',()=>{const a=C.ledgerAt(9800,'episode',2),b=C.ledgerAt(9800,'episode',10);close(a.exposed,b.exposed,.001);close(a.canopy,b.canopy,.001);close(a.leaf,b.leaf,.001);});
test('Spherical-drop drag predicts a lower lunar terminal speed',()=>{const a=C.dropletTerminalSpeed(.0007,1.62,1.45),b=C.dropletTerminalSpeed(.0007,9.80665,1.2);assert.ok(a>0&&b>a&&b<10);});
test('Wave frequency follows square-root gravity scaling',()=>close(C.waveOmega(.2,12,1.62)/C.waveOmega(.2,12,9.80665),Math.sqrt(1.62/9.80665)));
test('Wave gradients agree with centered finite differences',()=>{const x=3,z=7,t=24,w=C.waveAt(x,z,t),e=1e-4;close(w.nx,-(C.waveAt(x+e,z,t).y-C.waveAt(x-e,z,t).y)/(2*e),1e-7);close(w.nz,-(C.waveAt(x,z+e,t).y-C.waveAt(x,z-e,t).y)/(2*e),1e-7);});
test('Terrain is finite around every waypoint',()=>{for(const p of C.WAYPOINTS){const y=C.groundHeight(p.x,p.z);assert.ok(Number.isFinite(y)&&y>0);}});
test('Roof footprint separates dry inside from rain outside',()=>{assert.equal(C.roofMask(20,33),1);assert.equal(C.roofMask(20,20),0);});
test('Path centerline connects the requested places',()=>{for(const p of C.WAYPOINTS)assert.ok(C.pathDistance(p.x,p.z)<5);});
test('Procedural seeds are deterministic',()=>{const a=C.rng(123),b=C.rng(123);for(let i=0;i<100;i++)close(a(),b());});
test('The atlas stores all three inherited profiles and the full angular range',()=>{const d=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/atmosphere.json')));assert.equal(Object.keys(d.worlds).length,3);for(const w of Object.values(d.worlds)){assert.equal(w.suns[0],-90);assert.equal(w.suns.at(-1),90);assert.equal(w.width,33);assert.equal(w.height,41);assert.ok(w.quantization_error_relative_to_frame_max<.00025);}});
test('Dependency manifest pins the r186 ESM graph',()=>{const {REQUIRED,EDGES}=require('../src/loader.js');assert.deepEqual(REQUIRED,['three.core.js','three.module.js']);assert.equal(EDGES['three.module.js']['./three.core.js'],'three.core.js');});
test('Dependency verification rejects altered code before import',async()=>{const {verifyModule}=require('../src/loader.js');await assert.rejects(()=>verifyModule(new TextEncoder().encode('tampered'),{bytes:8,sha256:'0'.repeat(64)},'test'),/integrity/);});
test('Cloud displacement integrates a constant wind',()=>close(C.windDistance(3600,'clear'),C.weatherAt(0,'clear').wind*3600,1e-8));
test('Cloud displacement integrates varying wind reproducibly',()=>{close(C.windDistance(8100),C.windDistance(8100),1e-10);close(C.windDistance(8100,'episode',10),C.windDistance(8100,'episode',2),.02);assert.ok(C.windDistance(8200)>C.windDistance(8100));});
